test: added coverage checker and issue creator

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,6 +14,9 @@ jobs:
   test:
     name: 'Code quality and test'
     runs-on: ubuntu-latest
+    env:
+      COVERAGE_SINGLE: 60
+      COVERAGE_TOTAL: 60
     strategy:
       matrix:
         python-version: [3.10.6]
@@ -27,7 +30,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install ruff pytest pytest-cov
+          pip install ruff pytest flake8
           if [ -f app/requirements-dev.txt ]; then pip install -r app/requirements-dev.txt; fi
           if [ -f api_data_processing/requirements-dataprocessing.txt ]; then pip install -r api_data_processing/requirements-dataprocessing.txt; fi
       - name: Static Code Linting with ruff
@@ -39,41 +42,56 @@ jobs:
         uses: supercharge/mongodb-github-action@1.8.0
         with:
           mongodb-version: '6.0'
-      - name: Test with pytest
-        run: |
-          pytest --cov-config=.coveragerc --cov-report term --cov-report html:htmlcov --cov=app app/tests
-      - name: Upload code coverage html report
-        uses: actions/upload-artifact@v3
+      - name: pytester-cov
+        id: pytester-cov
+        uses: programmingwithalex/pytester-cov@main
         with:
-          name: code-coverage-report
-          path: htmlcov
+          pytest-root-dir: '.'
+          cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+    
+      - name: Coverage single fail - new issue
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: workflow-failed
+          body: ${{ steps.pytester-cov.outputs.output-table }}
+  
+      - name: Coverage single fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+          exit 1
+  
+      - name: Coverage total fail - new issue
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: workflow-failed
+          body: ${{ steps.pytester-cov.outputs.output-table }}
+  
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+          exit 1
+  
+      - name: Commit pytest coverage table
+        uses: peter-evans/commit-comment@main
+        with:
+          body: ${{ steps.pytester-cov.outputs.output-table }}
 
-  release:
-    name: 'Release to GitHub'
-    needs: test
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout repo
-      uses: actions/checkout@v2
-    - name: Setup Node.js
-      uses: actions/setup-node@v1
-      with:
-        node-version: 18
-    - name: Add plugin for conventional commits
-      run: npm install conventional-changelog-conventionalcommits
-      working-directory: ./.github/workflows
-    - name: Release to GitHub
-      working-directory: ./.github/workflows
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        GIT_AUTHOR_NAME: Janos Tordai
-        GIT_AUTHOR_EMAIL: tjanos88@gmail.com
-        GIT_COMMITTER_NAME: Janos Tordai
-        GIT_COMMITTER_EMAIL: tjanos88@gmail.com
-      run: npx semantic-release
+
   patch:
     name: 'Bump version number if needed and tag'
-    needs: release
+    needs: test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
